apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "info-system-service.fullname" . }}
  labels:
    app: info-system-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: info-system-service
  template:
    metadata:
      labels:
        app: info-system-service
    spec:
      containers:
        - name: info-system-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
