apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "info-system-service.fullname" . }}
  labels:
    app: info-system-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: info-system-service
  template:
    metadata:
      labels:
        app: info-system-service
    spec:
      containers:
        - name: info-system-service
<<<<<<< HEAD:charts/templates/deployment.yaml
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
=======
          image: saturn0912/node-service:20250325213123
>>>>>>> fe6455cca9e31d60002f8aeefc3037910d52df11:k8s/manifests/deployment.yaml
          ports:
            - containerPort: {{ .Values.service.targetPort }}
