apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-system-service
  labels:
    app: info-system-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: info-system-service
  template:
    metadata:
      labels:
        app: info-system-service
    spec:
      containers:
        - name: info-system-service
          image: saturn0912/node-service:1.0.0
          ports:
            - containerPort: 3002
