replicaCount: 1

image:
  repository: saturn0912/node-service
  tag: "12fb8b6795190af92a814698313a513a0f0146fe"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3002
  nodePort: 30080