apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Saturnnnnnnnnnnn/node-service.git
    targetRevision: HEAD
    path: charts
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
